services:
  - type: web
    name: lux-shirt-store
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false 
      - key: DATABASE_URL
        fromDatabase:
          name: lux-db
          property: connectionString

databases:
  - name: lux-db
    plan: free